# -*- coding: utf-8 -*-
"""utils.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16h5Xf4OSr-4jHxiW3aTBoWiD8ZHxhv41
"""

"""
script that load the book that the user called to open
then make the title of the book, author, and the genre lowercase.
return the naming as bookshelf
"""

import csv

#bookshelf data from the csv file
#credit: https://gist.github.com/jaidevd/23aef12e9bf56c618c41

def load_book(filename):
  bookshelf = []
  with open(filename) as file:
    shelf = csv.DictReader(file)
    for book in shelf:
      book['author_lowercase'] = book['Author'].lower()
      book['title_lowercase'] = book['Title'].lower()
      book['genre_lowercase'] = book['Genre'].lower()

      #update the bookshelf with new file list
      bookshelf.append(book)

  return bookshelf